
skip-check:
  - CKV2_K8S_6
    # Description: Minimize the admission of pods which lack an associated NetworkPolicy
    # Why we ignore: This is a work in progress and we shall be removing this once https://github.com/jalantechnologies/flask-react-template/issues/387 is complete 
  - CKV_K8S_43
    # Description: Image should use digest
    # Why we ignore: Since we are using dynamic image digest that is created from git commit hash, having this check doesn't fit our use case
  - CKV_K8S_14
    # Description: Image Tag should be fixed - not latest or blank   
    # Why we ignore: Since we are using dynamic image tag that is created from git commit hash, having this check doesn't fit our use case
  - CKV_K8S_35
    # Description: Prefer using secrets as files over secrets as environment variables   
    # Why we ignore: This is a configuration change that we cannot touch as of now with secrets being deployed dynamically
  - CKV_K8S_9
    # Description: Liveness Probe Should be Configured    
    # Why we ignore: Not required for every container 
  - CKV_K8S_8
    # Description: Readiness Probe Should be Configured    
    # Why we ignore: Not required for every container
