name: preview_deploy_main

on:
  push:
    branches:
      - punith/feat/add-permanent-preview-app

jobs:
  preview-deploy-main:
    uses: jalantechnologies/github-ci/.github/workflows/ci.yml@v2.5
    concurrency:
      group: ci-preview-main
      cancel-in-progress: true
    with:
      app_name: boilerplate-mern
      app_env: preview
      app_hostname: preview--boilerplate-mern.platform.jalantechnologies.com
      branch: punith/feat/add-permanent-preview-app
      checks: "['npm:lint', 'compose:test', 'compose:e2e']"
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      docker_username: ${{ vars.DOCKER_USERNAME }}
      sonar_host_url: ${{ vars.SONAR_HOST_URL }}
      do_cluster_id: ${{ vars.DO_CLUSTER_ID }}
    secrets:
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      doppler_token: ${{ secrets.DOPPLER_PREVIEW_TOKEN }}
      do_access_token: ${{ secrets.DO_ACCESS_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
